In [62]:
import pandas as pd

In [63]:
df = pd.read_csv("EcommData_CSV.csv", sep=";")

In [79]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [65]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102771 entries, 0 to 102770
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            102771 non-null  int64
 1   Age                    102771 non-null  int64
 2   Gender                 102771 non-null  str
 3   Item Purchased         102771 non-null  str
 4   Category               102771 non-null  str
 5   Purchase Amount (USD)  102771 non-null  str
 6   Location               102771 non-null  str
 7   Size                   102771 non-null  str
 8   Color                  102771 non-null  str
 9   Season                 102771 non-null  str
 10  Review Rating          102771 non-null  str
 11  Subscription Status    102771 non-null  str
 12  Shipping Type          102771 non-null  str
 13  Promo Code Used        102771 non-null  int64
 14  Previous Purchases     102771 non-null  int64
 15  Payment Method         102771 non-null  str
 16  Purchase Date          102771 non-null  str
 17  WeekdayNum             102771 non-null  int64
 18  Weekday                102771 non-null  str
 19  Weekend                102771 non-null  int64
 20  Churn                  102771 non-null  int64
dtypes: int64(7), str(14)
memory usage: 16.5 MB

In [66]:
df.head()
#Purchase Amount (USD) and Review Rating uses a comma as the decimal separator, so we need to convert it to a float. We can do this by replacing the comma with a dot and then converting the column to a float.
#Purchase Date is in the format of dd.mm.yyyy, so we need to convert it to a datetime format. We can do this by using the pd.to_datetime() function and specifying the format.

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Purchase Date,WeekdayNum,Weekday,Weekend,Churn
0,1,55,Male,Belt,Accessories,"46,9",Kentucky,L,Gray,Winter,5,Yes,Standard,0,14,Credit Card,7.01.2022,5,Friday,0,1
1,1,55,Male,Sweater,Clothing,"48,1",Kentucky,L,Green,Spring,1,Yes,Free Shipping,0,14,Credit Card,19.03.2022,6,Saturday,1,1
2,1,55,Male,Sweater,Clothing,"62,1",Kentucky,L,Green,Spring,5,Yes,Next Day Air,0,14,Debit Card,3.05.2022,2,Tuesday,0,1
3,1,55,Male,Belt,Accessories,"25,0",Kentucky,L,Turquoise,Summer,5,Yes,Free Shipping,0,14,Credit Card,7.05.2022,6,Saturday,1,1
4,1,55,Male,Sweater,Clothing,"89,8",Kentucky,L,Blue,Summer,5,Yes,2-Day Shipping,0,14,Google Pay,10.06.2022,5,Friday,0,1

In [67]:
df["Purchase Amount (USD)"] = df["Purchase Amount (USD)"].str.replace(",", ".").astype(float)
df["Review Rating"] = df["Review Rating"].str.replace(",", ".").astype(float)
df["Purchase Date"] = pd.to_datetime(df["Purchase Date"], format="%d.%m.%Y")

In [68]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Purchase Date,WeekdayNum,Weekday,Weekend,Churn
0,1,55,Male,Belt,Accessories,46.9,Kentucky,L,Gray,Winter,5.0,Yes,Standard,0,14,Credit Card,2022-01-07,5,Friday,0,1
1,1,55,Male,Sweater,Clothing,48.1,Kentucky,L,Green,Spring,1.0,Yes,Free Shipping,0,14,Credit Card,2022-03-19,6,Saturday,1,1
2,1,55,Male,Sweater,Clothing,62.1,Kentucky,L,Green,Spring,5.0,Yes,Next Day Air,0,14,Debit Card,2022-05-03,2,Tuesday,0,1
3,1,55,Male,Belt,Accessories,25.0,Kentucky,L,Turquoise,Summer,5.0,Yes,Free Shipping,0,14,Credit Card,2022-05-07,6,Saturday,1,1
4,1,55,Male,Sweater,Clothing,89.8,Kentucky,L,Blue,Summer,5.0,Yes,2-Day Shipping,0,14,Google Pay,2022-06-10,5,Friday,0,1

In [69]:
df.isnull().sum()
#There are no missing values, so we can continue with the analysis.

Customer ID              0
Age                      0
Gender                   0
Item Purchased           0
Category                 0
Purchase Amount (USD)    0
Location                 0
Size                     0
Color                    0
Season                   0
Review Rating            0
Subscription Status      0
Shipping Type            0
Promo Code Used          0
Previous Purchases       0
Payment Method           0
Purchase Date            0
WeekdayNum               0
Weekday                  0
Weekend                  0
Churn                    0
dtype: int64

In [70]:
#making all the column names lowercase and replacing spaces with underscores for better accessibility
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount_usd'})

In [94]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'purchase_date', 'weekdaynum', 'weekday', 'weekend', 'churn',
       'age_group', 'purchase_year', 'purchase_month', 'purchase_quarter',
       'quarter', 'year_quarter'],
      dtype='str')

In [95]:
#create a column age_group to categorize customers into different age groups based on their age. The age groups are defined as follows:
bins = [17, 29, 44, 59, 70]
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, include_lowest=True)

In [96]:
##Splitting the date purchased column into one for year, and month to be able to analyze the data by year and month
df['purchase_year'] = df['purchase_date'].dt.year
df['purchase_month'] = df['purchase_date'].dt.month
##Also adding the quarter of the year to be able to analyze the data by quarter
# Extract the quarter (1, 2, 3, or 4)
df['quarter'] = df['purchase_date'].dt.quarter
# Create a combined year-quarter column
df['year_quarter'] = (
    df['purchase_date'].dt.year.astype(str)
    + '-Q'
    + df['purchase_date'].dt.quarter.astype(str)
)

In [97]:
print(df[['purchase_date', 'purchase_year', 'quarter', 'year_quarter']].head(10))

  purchase_date  purchase_year  quarter year_quarter
0    2022-01-07           2022        1      2022-Q1
1    2022-03-19           2022        1      2022-Q1
2    2022-05-03           2022        2      2022-Q2
3    2022-05-07           2022        2      2022-Q2
4    2022-06-10           2022        2      2022-Q2
5    2022-08-28           2022        3      2022-Q3
6    2023-01-01           2023        1      2023-Q1
7    2023-02-11           2023        1      2023-Q1
8    2023-03-04           2023        1      2023-Q1
9    2023-03-05           2023        1      2023-Q1

In [98]:
#checking for duplicates in the data. We can do this by using the duplicated() function and then summing the result to get the total number of duplicates.
df.duplicated().sum()

np.int64(0)

In [99]:
#checking if the customer_id column has unique values. We can do this by using the nunique() function and comparing it to the total number of rows in the dataframe. If the two values are equal, then the customer_id column has unique values.
df['customer_id'].nunique() == len(df)

False

In [100]:
df.describe()

,customer_id,age,purchase_amount_usd,review_rating,promo_code_used,previous_purchases,purchase_date,weekdaynum,weekend,churn,purchase_year,purchase_month,purchase_quarter,quarter
count,102771.000000,102771.000000,102771.000000,102771.000000,102771.000000,102771.000000,102771,102771.000000,102771.000000,102771.000000,102771.000000,102771.000000,102771.000000,102771.000000
mean,1926.333148,44.405581,51.882230,3.852283,0.131924,33.270086,2023-08-23 15:27:04.345389,4.571630,0.384262,0.073455,2023.128071,6.699604,2.553892,2.553892
min,1.000000,18.000000,13.200000,1.000000,0.000000,1.000000,2022-01-01 00:00:00,1.000000,0.000000,0.000000,2022.000000,1.000000,1.000000,1.000000
25%,945.000000,31.000000,35.800000,3.000000,0.000000,25.000000,2022-12-15 00:00:00,3.000000,0.000000,0.000000,2022.000000,4.000000,2.000000,2.000000
50%,1921.000000,45.000000,48.700000,4.500000,0.000000,35.000000,2023-09-04 00:00:00,5.000000,0.000000,0.000000,2023.000000,7.000000,3.000000,3.000000
75%,2888.000000,57.000000,64.300000,5.000000,0.000000,44.000000,2024-05-14 00:00:00,6.000000,1.000000,0.000000,2024.000000,10.000000,4.000000,4.000000
max,3900.000000,70.000000,100.000000,5.000000,1.000000,50.000000,2024-12-31 00:00:00,7.000000,1.000000,1.000000,2024.000000,12.000000,4.000000,4.000000
std,1128.988782,15.187901,20.779942,1.499330,0.338410,12.096314,NaN,1.864296,0.486423,0.260882,0.812381,3.387374,1.090942,1.090942

In [101]:
#checking for inconsistencies in the data.

for col in ['gender', 'category', 'location', 'size', 'color', 'season', 'shipping_type', 'payment_method']:
    print(col)
    print(df[col].unique())
    print()

gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

category
<StringArray>
['Accessories', 'Clothing', 'Outerwear', 'Footwear']
Length: 4, dtype: str

location
<StringArray>
[      'Kentucky',          'Maine',  'Massachusetts',   'Rhode Island',
         'Oregon',        'Wyoming',        'Montana',      'Louisiana',
  'West Virginia',       'Missouri',       'Arkansas',         'Hawaii',
       'Delaware',  'New Hampshire',       'New York',        'Alabama',
    'Mississippi', 'North Carolina',     'California',       'Oklahoma',
        'Florida',          'Texas',         'Nevada',         'Kansas',
       'Colorado',   'North Dakota',       'Illinois',        'Indiana',
        'Arizona',         'Alaska',      'Tennessee',           'Ohio',
     'New Jersey',       'Maryland',        'Vermont',     'New Mexico',
 'South Carolina',          'Idaho',   'Pennsylvania',    'Connecticut',
           'Utah',       'Virginia',        'Georgia',       'Nebraska',
           'Iowa',   'South Dakota',      'Minnesota',     'Washington',
      'Wisconsin',       'Michigan']
Length: 50, dtype: str

size
<StringArray>
['L', 'S', 'M', 'XL']
Length: 4, dtype: str

color
<StringArray>
[     'Gray',     'Green', 'Turquoise',      'Blue',     'Beige',     'Brown',
       'Red',     'White',      'Pink',    'Maroon',      'Navy',    'Purple',
    'Yellow',    'Orange',     'Black',  'Charcoal',     'Olive',    'Silver']
Length: 18, dtype: str

season
<StringArray>
['Winter', 'Spring', 'Summer', 'Fall']
Length: 4, dtype: str

shipping_type
<StringArray>
['Standard', 'Free Shipping', 'Next Day Air', '2-Day Shipping', 'Express']
Length: 5, dtype: str

payment_method
<StringArray>
[  'Credit Card',    'Debit Card',    'Google Pay', 'Bank Transfer',
        'PayPal',          'Cash',         'Venmo',     'Apple Pay']
Length: 8, dtype: str

In [102]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/miniconda3/envs/data_project/lib/python3.12/site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /opt/miniconda3/envs/data_project/lib/python3.12/site-packages (2.0.52)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/miniconda3/envs/data_project/lib/python3.12/site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine

#Connecting to PostgreSQL database using SQLAlchemy. We will use the create_engine() function to create a connection to the database. 
username = "postgres" #default username for PostgreSQL
password = "password" #replace with your password
host = "localhost" #replace with your host
port = "5432" #default port for PostgreSQL
database = "EcommData" #replace with your database name

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

#Load DataFrame into PostgreSQL database using the to_sql() function. We will specify the name of the table, the connection to the database, and the if_exists parameter to specify what to do if the table already exists. We will set if_exists to 'replace' to replace the table if it already exists.
table_name = "consumer"
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"DataFrame loaded into table '{table_name}' in PostgreSQL database '{database}'.")

DataFrame loaded into table 'consumer' in PostgreSQL database 'EcommData'.

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102771 entries, 0 to 102770
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          102771 non-null  int64
 1   age                  102771 non-null  int64
 2   gender               102771 non-null  str
 3   item_purchased       102771 non-null  str
 4   category             102771 non-null  str
 5   purchase_amount_usd  102771 non-null  float64
 6   location             102771 non-null  str
 7   size                 102771 non-null  str
 8   color                102771 non-null  str
 9   season               102771 non-null  str
 10  review_rating        102771 non-null  float64
 11  subscription_status  102771 non-null  str
 12  shipping_type        102771 non-null  str
 13  promo_code_used      102771 non-null  int64
 14  previous_purchases   102771 non-null  int64
 15  payment_method       102771 non-null  str
 16  purchase_date        102771 non-null  datetime64[us]
 17  weekdaynum           102771 non-null  int64
 18  weekday              102771 non-null  str
 19  weekend              102771 non-null  int64
 20  churn                102771 non-null  int64
 21  age_group            102771 non-null  category
 22  purchase_year        102771 non-null  int32
 23  purchase_month       102771 non-null  int32
 24  purchase_quarter     102771 non-null  int32
 25  quarter              102771 non-null  int32
 26  year_quarter         102771 non-null  str
dtypes: category(1), datetime64[us](1), float64(2), int32(4), int64(7), str(12)
memory usage: 18.9 MB

In [106]:
# Exporting the SQL table to a CSV file to be able to use it in PowerBI for visualization. 
# We will use the to_csv() function to export the table to a CSV file. We will specify the name of the CSV file and set index to False to not include the index in the CSV file.
# Reading PostgreSQL table
df = pd.read_sql_query("SELECT * FROM consumer", engine)
df.to_csv("consumer_data.csv", index=False)

print("SQL table exported to CSV file 'consumer_data.csv'.")

SQL table exported to CSV file 'consumer_data.csv'.